### ISSUE TITLE
Ability to return JSON and call fsf-client as class

### ISSUE THREAD

**Issue by punkrokk** [akniffe1/fsf-client#3]
In a use case where I wished to call either an fsf-server or a fsf-server running in Docker, it was useful for me to take your standalone client, and call it from my own python script, and have it return json for machine parsing. I submitted PR #2 to address this use case. Please let me know if you have any questions.

**Comment by punkrokk** [comment]
@akniffe1 hey man - able to merge this?

**Comment by akniffe1** [comment]
@punkrokk Thanks for the contribution and starting the business of better integration for FSF! 

I apologize for the merge delay, you opened a can of worms that I hadn't spent any real time considering and got me thinking about other things that need to be done with the client (like #4 now). 

I appreciate the support!

**Comment by punkrokk** [comment]
:) Closed
